# Generated by Django 4.1.7 on 2023-09-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_date_match_matchdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1score', models.IntegerField(default=0)),
                ('team2score', models.IntegerField(default=0)),
                ('matchdate', models.DateField()),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1q', to='main.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2q', to='main.team')),
            ],
        ),
    ]
