# Generated by Django 4.1.7 on 2023-09-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_matchqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('goalsScored', models.IntegerField(default=0)),
                ('goalsLost', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('goalsScored', models.IntegerField(default=0)),
                ('mvpPoints', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('keeperPoints', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
