# Generated by Django 4.1.7 on 2023-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teamqueue_playerqueue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamqueue',
            name='league',
        ),
        migrations.AddField(
            model_name='matchqueue',
            name='playersData',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchqueue',
            name='teamsData',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='PlayerQueue',
        ),
        migrations.DeleteModel(
            name='TeamQueue',
        ),
    ]
