# Generated by Django 4.1.7 on 2023-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_teamqueue_league_matchqueue_playersdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='main.player'),
        ),
        migrations.DeleteModel(
            name='MatchQueue',
        ),
    ]
