# Generated by Django 4.1.7 on 2023-09-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_match_players_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='keeperPoints',
            field=models.FloatField(default=0),
        ),
    ]
